apiVersion: v1
kind: Pod
metadata:
  name: har-ambiq-model
spec:
  containers:
  - name: har-ambiq-model
    image: yuy080/har-base-docker
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
    command: ["/bin/sh", "-c", "git clone https://github.com/ersp-2024-pannuto/human-activity-recognition-base-model.git"]
